<?php
/**
 * Sidebars
 *
 * Register Sidebars
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Register widgetized area and update sidebar with default widgets.
 */
// function responsive_mobile_widgets_init_redo() {
	register_sidebar( array(
		'name'          => __( 'Home Widget 4', 'responsive-mobile' ),
		'description'   => __( 'Area 9 - sidebar-home.php - Displays on the Home Page', 'responsive-mobile' ),
		'id'            => 'home-widget-4',
		'before_title'  => '<div id="widget-title-four" class="widget-title-home"><h3 class="widget-title-home">',
		'after_title'   => '</h3></div>',
		'before_widget' => '<div id="%1$s" class="widget-wrapper %2$s">',
		'after_widget'  => '</div>'
	) );
// }
// add_action( 'widgets_init', 'responsive_mobile_widgets_init_redo' );
